Development checkpoint.

diff --git a/bin/mksh_setup b/bin/mksh_setup
--- a/bin/mksh_setup
+++ b/bin/mksh_setup
@@ -28,6 +28,6 @@ case "$THIS_ACTION" in
     ;;
 esac
 
+echo "!!! Action not found: \"$THIS_NAME\", Arguments: $@" >&2
+exit 1
 
-echo "!!! Action not found: $@" >&2
-return 1
